@startuml

[we]

[we] --> () "information" : must process

[we] --> () "things" : can do

[we] --> () "information" : collect
[you]

[you] --> () "part" : are


[you] --> () "features" : use



[we] --> () "information" : use


[we] --> () "cookies" : use

[we] --> () "data" : receive



[we] --> () "information" : connect

[you] --> () "control" : will have

[we] --> () "data" : use

[we] --> () "information" : analyze

[we] --> () "access" : can provide
[they]

[they] --> () "information" : can receive

[we] --> () "developers" : will remove
[them]

[them] --> () "interactions" : understand

[we] --> () "advertisers" : provide

[we] --> () "information" : provide

[we] --> () "information" : process

[we] --> () "data" : store

[we] --> () "things" : delete


[we] --> () "changes" : make

[you] --> () "questions" : have

[we] --> () "disputes" : may resolve
@enduml
